-- CreateTable
CREATE TABLE "lpm" (
    "Product Id" UUID NOT NULL,
    "Product Type" VARCHAR(11) NOT NULL,
    "Product Title" VARCHAR(46) NOT NULL,
    "Product Version" VARCHAR(19),
    "Product Display Artist" VARCHAR(43) NOT NULL,
    "Parent Label" VARCHAR(30),
    "label" VARCHAR(9) NOT NULL,
    "Original Release Date" DATE,
    "Release Date" DATE NOT NULL,
    "UPC" INTEGER NOT NULL,
    "Catalog " VARCHAR(15) NOT NULL,
    "Product Price Tier" VARCHAR(25),
    "Product Genre" VARCHAR(24) NOT NULL,
    "Submission Status" VARCHAR(8) NOT NULL,
    "Product C Line" VARCHAR(53) NOT NULL,
    "Product P Line" VARCHAR(53) NOT NULL,
    "PreOrder Date" DATE,
    "Exclusives" VARCHAR(30),
    "ExplicitLyrics" VARCHAR(2) NOT NULL,
    "Product Play Link" VARCHAR(42),
    "Liner Notes" VARCHAR(1164),
    "Primary Metadata Language" VARCHAR(23) NOT NULL,
    "Compilation" VARCHAR(5),
    "PDF Booklet" VARCHAR(30),
    "Timed Release Date" VARCHAR(30),
    "Timed Release Music Services" VARCHAR(30),
    "Last Process Date" DATE NOT NULL,
    "Import Date" DATE NOT NULL,
    "Created By" VARCHAR(29) NOT NULL,
    "Last Modified" DATE NOT NULL,
    "Submitted At" DATE NOT NULL,
    "Submitted By" VARCHAR(30),
    "Vevo Channel" VARCHAR(18),
    "TrackType" VARCHAR(10) NOT NULL,
    "Track Id" VARCHAR(24) NOT NULL,
    "Track Volume" BOOLEAN NOT NULL,
    "Track Number" INTEGER NOT NULL,
    "Track Name" VARCHAR(46) NOT NULL,
    "Track Version" VARCHAR(19),
    "Track Display Artist" VARCHAR(43) NOT NULL,
    "Isrc" VARCHAR(12) NOT NULL,
    "Track Price Tier" VARCHAR(23),
    "Track Genre" VARCHAR(24) NOT NULL,
    "Audio Language" VARCHAR(23) NOT NULL,
    "Track C Line" VARCHAR(53) NOT NULL,
    "Track P Line" VARCHAR(53) NOT NULL,
    "WritersComposers" VARCHAR(610) NOT NULL,
    "PublishersCollection Societies" VARCHAR(139) NOT NULL,
    "Withhold Mechanicals" VARCHAR(2) NOT NULL,
    "PreOrder Type" VARCHAR(8),
    "Instant Gratification Date" VARCHAR(30),
    "Duration" VARCHAR(8) NOT NULL,
    "Sample Start Time" VARCHAR(8),
    "Explicit Lyrics" VARCHAR(3) NOT NULL,
    "Album Only" VARCHAR(2) NOT NULL,
    "Lyrics" VARCHAR(1967),
    "AdditionalContributorsPerforming" VARCHAR(103),
    "AdditionalContributorsNonPerforming" VARCHAR(520),
    "Producers" VARCHAR(91),
    "Continuous Mix" VARCHAR(5),
    "Continuously Mixed Individual Song" VARCHAR(5),
    "Track Play Link" VARCHAR(44),

    CONSTRAINT "lpm_pkey" PRIMARY KEY ("Product Id")
);

-- CreateIndex
CREATE UNIQUE INDEX "lpm_Product Type_key" ON "lpm"("Product Type");
