-- AlterTable
ALTER TABLE "DistributionStatement" ALTER COLUMN "Venta" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "Regalias Artisticas" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "Copyright" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "Cuota Administracion" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "Costo Carga" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "Otros Costos" SET DATA TYPE DOUBLE PRECISION;
