/*
  Warnings:

  - You are about to drop the column `AdditionalContributorsNonPerforming` on the `lpm` table. All the data in the column will be lost.
  - You are about to drop the column `AdditionalContributorsPerforming` on the `lpm` table. All the data in the column will be lost.
  - You are about to drop the column `Catalog ` on the `lpm` table. All the data in the column will be lost.
  - You are about to drop the column `PreOrder Date` on the `lpm` table. All the data in the column will be lost.
  - You are about to drop the column `PreOrder Type` on the `lpm` table. All the data in the column will be lost.
  - You are about to drop the column `PublishersCollection Societies` on the `lpm` table. All the data in the column will be lost.
  - You are about to drop the column `WritersComposers` on the `lpm` table. All the data in the column will be lost.
  - You are about to drop the column `label` on the `lpm` table. All the data in the column will be lost.
  - You are about to drop the column `productId` on the `lpm` table. All the data in the column will be lost.
  - The `UPC` column on the `lpm` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - The `Track Volume` column on the `lpm` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - The `Track Number` column on the `lpm` table would be dropped and recreated. This will lead to data loss if there is data in the column.

*/
-- AlterTable
ALTER TABLE "lpm" DROP COLUMN "AdditionalContributorsNonPerforming",
DROP COLUMN "AdditionalContributorsPerforming",
DROP COLUMN "Catalog ",
DROP COLUMN "PreOrder Date",
DROP COLUMN "PreOrder Type",
DROP COLUMN "PublishersCollection Societies",
DROP COLUMN "WritersComposers",
DROP COLUMN "label",
DROP COLUMN "productId",
ADD COLUMN     "Catalog #" TEXT,
ADD COLUMN     "Label" TEXT,
ADD COLUMN     "Pre-Order Date" TEXT,
ADD COLUMN     "Pre-Order Type" TEXT,
ADD COLUMN     "Product Id" TEXT,
ADD COLUMN     "Publishers/Collection Societies" TEXT,
ADD COLUMN     "Writers/Composers" TEXT,
ALTER COLUMN "Product Type" DROP NOT NULL,
ALTER COLUMN "Product Type" SET DATA TYPE TEXT,
ALTER COLUMN "Product Title" DROP NOT NULL,
ALTER COLUMN "Product Title" SET DATA TYPE TEXT,
ALTER COLUMN "Product Version" SET DATA TYPE TEXT,
ALTER COLUMN "Product Display Artist" DROP NOT NULL,
ALTER COLUMN "Product Display Artist" SET DATA TYPE TEXT,
ALTER COLUMN "Parent Label" SET DATA TYPE TEXT,
ALTER COLUMN "Original Release Date" SET DATA TYPE TEXT,
ALTER COLUMN "Release Date" DROP NOT NULL,
ALTER COLUMN "Release Date" SET DATA TYPE TEXT,
DROP COLUMN "UPC",
ADD COLUMN     "UPC" DOUBLE PRECISION,
ALTER COLUMN "Product Price Tier" SET DATA TYPE TEXT,
ALTER COLUMN "Product Genre" DROP NOT NULL,
ALTER COLUMN "Product Genre" SET DATA TYPE TEXT,
ALTER COLUMN "Submission Status" DROP NOT NULL,
ALTER COLUMN "Submission Status" SET DATA TYPE TEXT,
ALTER COLUMN "Product C Line" DROP NOT NULL,
ALTER COLUMN "Product C Line" SET DATA TYPE TEXT,
ALTER COLUMN "Product P Line" DROP NOT NULL,
ALTER COLUMN "Product P Line" SET DATA TYPE TEXT,
ALTER COLUMN "Exclusives" SET DATA TYPE TEXT,
ALTER COLUMN "ExplicitLyrics" DROP NOT NULL,
ALTER COLUMN "ExplicitLyrics" SET DATA TYPE TEXT,
ALTER COLUMN "Product Play Link" SET DATA TYPE TEXT,
ALTER COLUMN "Liner Notes" SET DATA TYPE TEXT,
ALTER COLUMN "Primary Metadata Language" DROP NOT NULL,
ALTER COLUMN "Primary Metadata Language" SET DATA TYPE TEXT,
ALTER COLUMN "Compilation" SET DATA TYPE TEXT,
ALTER COLUMN "PDF Booklet" SET DATA TYPE TEXT,
ALTER COLUMN "Timed Release Date" SET DATA TYPE TEXT,
ALTER COLUMN "Timed Release Music Services" SET DATA TYPE TEXT,
ALTER COLUMN "Last Process Date" DROP NOT NULL,
ALTER COLUMN "Last Process Date" SET DATA TYPE TEXT,
ALTER COLUMN "Import Date" DROP NOT NULL,
ALTER COLUMN "Import Date" SET DATA TYPE TEXT,
ALTER COLUMN "Created By" DROP NOT NULL,
ALTER COLUMN "Created By" SET DATA TYPE TEXT,
ALTER COLUMN "Last Modified" DROP NOT NULL,
ALTER COLUMN "Last Modified" SET DATA TYPE TEXT,
ALTER COLUMN "Submitted At" DROP NOT NULL,
ALTER COLUMN "Submitted At" SET DATA TYPE TEXT,
ALTER COLUMN "Submitted By" SET DATA TYPE TEXT,
ALTER COLUMN "Vevo Channel" SET DATA TYPE TEXT,
ALTER COLUMN "TrackType" DROP NOT NULL,
ALTER COLUMN "TrackType" SET DATA TYPE TEXT,
ALTER COLUMN "Track Id" DROP NOT NULL,
ALTER COLUMN "Track Id" SET DATA TYPE TEXT,
DROP COLUMN "Track Volume",
ADD COLUMN     "Track Volume" INTEGER,
DROP COLUMN "Track Number",
ADD COLUMN     "Track Number" INTEGER,
ALTER COLUMN "Track Name" DROP NOT NULL,
ALTER COLUMN "Track Name" SET DATA TYPE TEXT,
ALTER COLUMN "Track Version" SET DATA TYPE TEXT,
ALTER COLUMN "Track Display Artist" DROP NOT NULL,
ALTER COLUMN "Track Display Artist" SET DATA TYPE TEXT,
ALTER COLUMN "Isrc" DROP NOT NULL,
ALTER COLUMN "Isrc" SET DATA TYPE TEXT,
ALTER COLUMN "Track Price Tier" SET DATA TYPE TEXT,
ALTER COLUMN "Track Genre" DROP NOT NULL,
ALTER COLUMN "Track Genre" SET DATA TYPE TEXT,
ALTER COLUMN "Audio Language" DROP NOT NULL,
ALTER COLUMN "Audio Language" SET DATA TYPE TEXT,
ALTER COLUMN "Track C Line" DROP NOT NULL,
ALTER COLUMN "Track C Line" SET DATA TYPE TEXT,
ALTER COLUMN "Track P Line" DROP NOT NULL,
ALTER COLUMN "Track P Line" SET DATA TYPE TEXT,
ALTER COLUMN "Withhold Mechanicals" DROP NOT NULL,
ALTER COLUMN "Withhold Mechanicals" SET DATA TYPE TEXT,
ALTER COLUMN "Instant Gratification Date" SET DATA TYPE TEXT,
ALTER COLUMN "Duration" DROP NOT NULL,
ALTER COLUMN "Duration" SET DATA TYPE TEXT,
ALTER COLUMN "Sample Start Time" SET DATA TYPE TEXT,
ALTER COLUMN "Explicit Lyrics" DROP NOT NULL,
ALTER COLUMN "Explicit Lyrics" SET DATA TYPE TEXT,
ALTER COLUMN "Album Only" DROP NOT NULL,
ALTER COLUMN "Album Only" SET DATA TYPE TEXT,
ALTER COLUMN "Lyrics" SET DATA TYPE TEXT,
ALTER COLUMN "Producers" SET DATA TYPE TEXT,
ALTER COLUMN "Continuous Mix" SET DATA TYPE TEXT,
ALTER COLUMN "Continuously Mixed Individual Song" SET DATA TYPE TEXT,
ALTER COLUMN "Track Play Link" SET DATA TYPE TEXT;
